[colors.primary]
background = "#101010"
foreground = "#525252"

[colors.cursor]
text = '#101010'
cursor = '#525252'

[colors.normal]
black   = '#101010'
red     = '#7c7c7c'
green   = '#8e8e8e'
yellow  = '#a0a0a0'
blue    = '#686868'
magenta = '#747474'
cyan    = '#868686'
white   = '#b9b9b9'

[colors.bright]
black   = '#525252'
red     = '#7c7c7c'
green   = '#8e8e8e'
yellow  = '#a0a0a0'
blue    = '#686868'
magenta = '#747474'
cyan    = '#868686'
white   = '#f7f7f7'
